spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/membermgmtdb
    username: root
    password: Venkat@27
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8889/eureka